include: package:lint/analysis_options_package.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"

linter:
  rules:
    avoid_classes_with_only_static_members: false