name: taberu
description: Allows your local customers to order dishes through an easy-to-use digital menu with a modern design.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.6.9
  cached_network_image: ^2.5.1
  cloud_firestore: ^0.16.0
  cupertino_icons: ^0.1.3
  curved_navigation_bar: ^0.3.7
  dartz: ^0.9.2
  dropdown_search: ^0.4.8
  easy_localization: ^2.3.3
  firebase_core: ^0.7.0
  flushbar: ^1.10.4
  flutter_bloc: ^6.1.1
  flutter_staggered_grid_view: ^0.3.4
  freezed_annotation: ^0.12.0
  get_it: ^5.0.4
  google_fonts: ^1.1.1
  flutter_hooks: ^0.15.0
  injectable: ^1.0.7
  json_annotation: ^3.1.1
  kt_dart: ^0.8.0
  rxdart: ^0.25.0
  shared_preferences: ^0.5.12+4
  smooth_page_indicator: ^0.2.3
  stilo: ^1.1.2
  url_launcher: ^5.7.10
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator: ^0.6.10
  freezed: ^0.12.6
  injectable_generator: ^1.0.7
  json_serializable: ^3.5.1
  lint: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/restaurant_menu/
    - assets/translations/
