name: taberu
description: Allows your local customers to order dishes through an easy-to-use digital menu with a modern design.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  another_flushbar: ^1.10.23
  auto_route: ^2.2.0
  cached_network_image: ^3.0.0
  cloud_firestore: ^2.2.1
  cupertino_icons: ^1.0.3
  curved_navigation_bar: ^0.4.0-nullsafety.0
  dartz: ^0.10.0-nullsafety.2
  dropdown_search: ^0.6.1
  easy_localization: ^3.0.0
  enum_to_string: ^2.0.1
  firebase_core: ^1.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_hooks: ^0.17.0
  flutter_staggered_grid_view: ^0.4.0
  freezed_annotation: ^0.14.2
  get_it: ^7.1.3
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.6
  injectable: ^1.4.1
  json_annotation: ^4.0.1
  kt_dart: ^0.9.1
  rxdart: ^0.27.1
  shared_preferences: ^2.0.6
  smooth_page_indicator: ^0.3.0-nullsafety.0
  stilo: ^2.0.0
  url_launcher: ^6.0.6
  uuid: ^3.0.4

dev_dependencies:
  auto_route_generator: ^2.1.0
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  injectable_generator: ^1.4.1
  json_serializable: ^4.1.3
  lint: ^1.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/restaurant_menu/
    - assets/translations/
  fonts:
    - family: Taberu
      fonts:
        - asset: assets/fonts/Taberu.ttf
